/* Gemeinsame Mehrgeräte-Synchronisierung mit Supabase und lokalem Fallback */
const AIU_SYNC={enabled:false,client:null,classCode:'SRL5-AIU',lastStateStamp:'',pollTimer:null};
const AIU_DEVICE_KEY='aiu-device-id';
function aiuDeviceId(){let id=localStorage.getItem(AIU_DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(AIU_DEVICE_KEY,id)}return id}
function aiuSyncConfig(){return window.AIU_SYNC_CONFIG||{enabled:false}}
function aiuSyncStatus(text,online=false){let badge=document.getElementById('syncStatus');if(!badge){badge=document.createElement('div');badge.id='syncStatus';badge.className='session-pill';const host=document.querySelector('.header-status');if(host)host.appendChild(badge)}if(badge){badge.textContent=text;badge.classList.toggle('open',online)}}
async function syncInit(){const cfg=aiuSyncConfig();AIU_SYNC.classCode=cfg.classCode||'SRL5-AIU';if(!cfg.enabled||!cfg.supabaseUrl||!cfg.supabaseAnonKey||!window.supabase){aiuSyncStatus('💻 Nur dieses Gerät',false);return false}try{AIU_SYNC.client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:false,autoRefreshToken:false}});const {error}=await AIU_SYNC.client.from('aiu_state').select('class_code').eq('class_code',AIU_SYNC.classCode).limit(1);if(error)throw error;AIU_SYNC.enabled=true;aiuSyncStatus('☁️ Geräte verbunden',true);return true}catch(error){console.error('Supabase-Verbindung fehlgeschlagen',error);AIU_SYNC.enabled=false;aiuSyncStatus('⚠️ Offline-Modus',false);return false}}
function runtimeForRemote(value){return JSON.parse(JSON.stringify(value||{}))}
async function syncLoadRuntime(localRuntime){if(!AIU_SYNC.enabled)return localRuntime;const {data,error}=await AIU_SYNC.client.from('aiu_state').select('runtime,updated_at').eq('class_code',AIU_SYNC.classCode).maybeSingle();if(error)throw error;if(!data){await syncSaveRuntime(localRuntime);return localRuntime}AIU_SYNC.lastStateStamp=data.updated_at||'';return {...localRuntime,...(data.runtime||{})}}
async function syncSaveRuntime(value){if(!AIU_SYNC.enabled){saveRuntimeLocal();return}const payload={class_code:AIU_SYNC.classCode,runtime:runtimeForRemote(value),updated_at:new Date().toISOString()};const {data,error}=await AIU_SYNC.client.from('aiu_state').upsert(payload,{onConflict:'class_code'}).select('updated_at').single();if(error)throw error;AIU_SYNC.lastStateStamp=data.updated_at||payload.updated_at;saveRuntimeLocal()}
async function syncRefreshRuntime(){if(!AIU_SYNC.enabled)return;try{const {data,error}=await AIU_SYNC.client.from('aiu_state').select('runtime,updated_at').eq('class_code',AIU_SYNC.classCode).maybeSingle();if(error||!data||data.updated_at===AIU_SYNC.lastStateStamp)return;AIU_SYNC.lastStateStamp=data.updated_at||'';runtime={...runtime,...(data.runtime||{})};saveRuntimeLocal();render()}catch(error){console.warn('Synchronisierung pausiert',error);aiuSyncStatus('⚠️ Verbindung unterbrochen',false)}}
function syncStartPolling(){if(!AIU_SYNC.enabled||AIU_SYNC.pollTimer)return;AIU_SYNC.pollTimer=setInterval(syncRefreshRuntime,Math.max(2500,Number(aiuSyncConfig().pollIntervalMs)||5000))}

/* Lokale IndexedDB als Cache und Offline-Fallback */
let aiuDbPromise;
function aiuLocalDb(){if(!aiuDbPromise)aiuDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('kiu-begleitapp-v2',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('submissions'))request.result.createObjectStore('submissions',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return aiuDbPromise}
async function aiuStore(mode='readonly'){return(await aiuLocalDb()).transaction('submissions',mode).objectStore('submissions')}
async function aiuReq(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function aiuLocalPut(value){return aiuReq((await aiuStore('readwrite')).put(value))}
async function aiuLocalGet(id){return aiuReq((await aiuStore()).get(id))}
async function aiuLocalAll(){return aiuReq((await aiuStore()).getAll())}
async function aiuLocalDelete(id){return aiuReq((await aiuStore('readwrite')).delete(id))}
async function aiuLocalClear(){return aiuReq((await aiuStore('readwrite')).clear())}
function aiuExtension(type,mime=''){if(type==='audio')return mime.includes('mp4')?'m4a':'webm';if(mime.includes('jpeg'))return'jpg';return'png'}
function aiuRowToSubmission(row){let mediaUrl='';if(row.media_path&&AIU_SYNC.client)mediaUrl=AIU_SYNC.client.storage.from('aiu-media').getPublicUrl(row.media_path).data.publicUrl;return{id:row.id,week:row.week,missionId:row.mission_id,missionTitle:row.mission_title,area:row.area,resource:row.resource,author:row.author||'',text:row.text||'',type:row.type,mime:row.mime||'',mediaPath:row.media_path||'',mediaUrl,createdAt:row.created_at,status:row.status||'pending'}}
async function dbPut(value){await aiuLocalPut(value);if(!AIU_SYNC.enabled)return value;let mediaPath=value.mediaPath||'';if(value.blob&&!mediaPath){mediaPath=`${AIU_SYNC.classCode}/${value.id}.${aiuExtension(value.type,value.mime)}`;const {error:uploadError}=await AIU_SYNC.client.storage.from('aiu-media').upload(mediaPath,value.blob,{contentType:value.mime||value.blob.type,upsert:true});if(uploadError)throw uploadError}const row={id:value.id,class_code:AIU_SYNC.classCode,week:value.week,mission_id:value.missionId,mission_title:value.missionTitle,area:value.area,resource:value.resource,author:value.author||'',text:value.text||'',type:value.type,mime:value.mime||'',media_path:mediaPath||null,status:value.status||'pending',created_at:value.createdAt||new Date().toISOString()};const {error}=await AIU_SYNC.client.from('aiu_submissions').upsert(row,{onConflict:'id'});if(error)throw error;return value}
async function dbAll(){if(!AIU_SYNC.enabled)return aiuLocalAll();const {data,error}=await AIU_SYNC.client.from('aiu_submissions').select('*').eq('class_code',AIU_SYNC.classCode).order('created_at',{ascending:false});if(error)throw error;return(data||[]).map(aiuRowToSubmission)}
async function dbGet(id){if(!AIU_SYNC.enabled)return aiuLocalGet(id);const {data,error}=await AIU_SYNC.client.from('aiu_submissions').select('*').eq('class_code',AIU_SYNC.classCode).eq('id',id).maybeSingle();if(error)throw error;return data?aiuRowToSubmission(data):null}
async function dbDelete(id){const local=await aiuLocalGet(id);await aiuLocalDelete(id);if(!AIU_SYNC.enabled)return;const remote=await dbGet(id);const path=remote?.mediaPath||local?.mediaPath;if(path)await AIU_SYNC.client.storage.from('aiu-media').remove([path]);const {error}=await AIU_SYNC.client.from('aiu_submissions').delete().eq('class_code',AIU_SYNC.classCode).eq('id',id);if(error)throw error}
async function dbClear(){return aiuLocalClear()}
async function syncDownloadSubmission(submission){if(submission.blob)return submission.blob;if(!submission.mediaUrl)return null;const response=await fetch(submission.mediaUrl);if(!response.ok)throw new Error('Mediendatei konnte nicht geladen werden');return response.blob()}

/* Gemeinsame Abstimmungen */
async function syncCastVote(weekNumber,choice){if(!AIU_SYNC.enabled){const key=`${weekNumber}-${choice}`;runtime.votes[key]=Number(runtime.votes[key]||0)+1;saveRuntimeLocal();return}const {error}=await AIU_SYNC.client.from('aiu_votes').insert({id:crypto.randomUUID(),class_code:AIU_SYNC.classCode,week:weekNumber,choice,device_id:aiuDeviceId(),created_at:new Date().toISOString()});if(error)throw error}
async function syncVoteCounts(weekNumber,choiceCount){if(!AIU_SYNC.enabled)return Array.from({length:choiceCount},(_,i)=>Number(runtime.votes[`${weekNumber}-${i}`]||0));const {data,error}=await AIU_SYNC.client.from('aiu_votes').select('choice').eq('class_code',AIU_SYNC.classCode).eq('week',weekNumber);if(error)throw error;const counts=Array(choiceCount).fill(0);(data||[]).forEach(row=>{if(Number.isInteger(row.choice)&&row.choice>=0&&row.choice<counts.length)counts[row.choice]++});return counts}
async function syncResetVotes(weekNumber){if(!AIU_SYNC.enabled){Object.keys(runtime.votes).filter(key=>key.startsWith(`${weekNumber}-`)).forEach(key=>delete runtime.votes[key]);saveRuntimeLocal();return}const {error}=await AIU_SYNC.client.from('aiu_votes').delete().eq('class_code',AIU_SYNC.classCode).eq('week',weekNumber);if(error)throw error}
