'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const LS_RUNTIME='kiu-v2-runtime', LS_AUTH='kiu-v2-teacher-auth';
let CFG=null, runtime=null, currentWeek=null, currentMission=null, currentOutput='text', mediaBlob=null, mediaRecorder=null, mediaChunks=[], drawCtx=null;
const OUTPUT={text:['✍️','Text'],drawing:['🎨','Zeichnung'],photo:['📷','Foto'],audio:['🎙️','Audio']};
const AREA={werft:['🔨','Werft'],kartenraum:['🗺️','Kartenraum'],logbuch:['📖','Logbuch']};
const RES_COLOR={antrieb:'#2f7a55',wissen:'#2876a3',zusammenhalt:'#d46e2a'};
function esc(v=''){const d=document.createElement('div');d.textContent=String(v);return d.innerHTML}
function clone(v){return JSON.parse(JSON.stringify(v))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function formatDate(v){try{return new Date(v).toLocaleDateString('de-DE',{day:'numeric',month:'long',year:'numeric'})}catch{return v}}
function download(name,content,type='application/json'){const b=content instanceof Blob?content:new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadConfig(){try{const r=await fetch('./config.json',{cache:'no-store'});if(!r.ok)throw 0;CFG=await r.json()}catch(e){alert('config.json konnte nicht geladen werden. Bitte prüfe das Deployment.');throw e}}
function defaultRuntime(){return{week:CFG.game.currentWeek,resources:Object.fromEntries(Object.entries(CFG.resources).map(([k,v])=>[k,v.value])),studentUntil:0,councilOpen:false,votes:{},upgrades:Object.fromEntries(CFG.shipUpgrades.map(x=>[x.id,!!x.unlocked])),localLogbook:[]}}
function loadRuntime(){try{runtime={...defaultRuntime(),...JSON.parse(localStorage.getItem(LS_RUNTIME)||'{}')}}catch{runtime=defaultRuntime()}saveRuntimeLocal()}
function saveRuntimeLocal(){localStorage.setItem(LS_RUNTIME,JSON.stringify(runtime))}
function week(){return CFG.weeks.find(w=>w.number===Number(runtime.week))||CFG.weeks[0]}
function unlocked(key){return week().unlocks.includes(key)}
function studentOpen(){return runtime.studentUntil>Date.now()}
function updateSession(){const remaining=Math.max(0,runtime.studentUntil-Date.now());const mins=Math.ceil(remaining/60000);const open=remaining>0;['#sessionPill','#missionSessionPill'].forEach(s=>{const e=$(s);if(!e)return;e.textContent=open?`🟢 Beiträge offen · ${mins} Min.`:'🔒 Beiträge geschlossen';e.classList.toggle('open',open)});const teacherText=$('#sessionTeacherText');if(teacherText)teacherText.textContent=open?`Schülerzugang noch etwa ${mins} Minuten geöffnet.`:'Beiträge sind geschlossen.';if(!open&&runtime.studentUntil){runtime.studentUntil=0;saveRuntimeLocal();if(typeof syncSaveRuntime==='function')syncSaveRuntime(runtime).catch(()=>{})}}
function gotoView(name){if(name==='lehrer'&&!sessionStorage.getItem(LS_AUTH)){openPin();return}if(!unlocked(name)&&!['deck','lehrer','ausbau'].includes(name)){toast('Dieser Bereich ist noch verschlossen.');return}$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='lehrer')renderTeacher();if(name==='rat')renderCouncil();if(name==='logbuch')renderLogbook()}
function render(){currentWeek=week();$('#headerEmblem').textContent=CFG.ship.emblem;$('#headerShip').textContent=CFG.ship.name;$('#headerSub').textContent=`${CFG.app.subtitle} · ${CFG.school.className}`;$('#headerWeek').textContent=`Woche ${currentWeek.number} · ${currentWeek.short}`;$('#headerPosition').textContent=CFG.ship.position;$('#phaseLabel').textContent=currentWeek.phase==='einfuehrung'?`Einführung ${currentWeek.number} von 6`:`Etappe ${currentWeek.number}`;$('#chapterTitle').textContent=currentWeek.chapter;$('#chapterStory').textContent=currentWeek.story;$('#routineTitle').textContent=currentWeek.routine.title;$('#routineText').textContent=currentWeek.routine.text;$('#unlockTitle').textContent=currentWeek.new_unlock;$('#unlockText').textContent=currentWeek.number<6?'Weitere Bereiche werden in den nächsten Wochen sichtbar.':'Das vollständige Spielsystem ist aktiv.';renderWeekDots();renderLocks();renderResources();renderMissions();renderMap();renderLogbook();renderCouncil();renderUpgrades();updateSession()}
function renderWeekDots(){const max=currentWeek.phase==='einfuehrung'?6:15;$('#weekDots').innerHTML=Array.from({length:max},(_,i)=>`<span class="week-dot ${i+1<currentWeek.number?'done':i+1===currentWeek.number?'now':''}"></span>`).join('')}
function renderLocks(){$$('.hotspot[data-go],.nav-btn').forEach(b=>{const k=b.dataset.go||b.dataset.view;b.classList.toggle('locked',!unlocked(k)&&k!=='deck')});$('#resourceHotspot').classList.toggle('locked',!['antrieb','wissen','zusammenhalt'].some(unlocked));$('#resourceHotspot').onclick=()=>{document.querySelector('#gemsSection').scrollIntoView({behavior:'smooth',block:'center'})};$('#teacherHotspot').onclick=()=>gotoView('lehrer')}
function renderResources(){const keys=['antrieb','wissen','zusammenhalt'];$('#resourceCards').innerHTML=keys.map(k=>{const r=CFG.resources[k],val=Number(runtime.resources[k]||0),is=unlocked(k),mil=currentWeek.milestones?.[k],pct=Math.min(100,val/r.maximum*100);let stones='';for(let i=0;i<Math.min(val,20);i++)stones+=`<span class="stone" style="background:${RES_COLOR[k]}"></span>`;return `<article class="card resource ${is?'':'locked'}" style="opacity:${is?1:.48}"><div class="row spread"><h3>${r.icon} ${r.label}</h3><span>${is?'':'🔒'}</span></div><div class="resource-value" style="color:${RES_COLOR[k]}">${is?val:'–'}</div><div class="bar"><div style="width:${is?pct:0}%;background:${RES_COLOR[k]}"></div></div><div class="res-stones">${is?stones:''}</div><p class="small muted">${mil?`${mil.target} benötigt: ${esc(mil.reward)}`:is?'Gemeinsamer Fortschritt der Besatzung.':'Wird in einer Einführungswoche geöffnet.'}</p></article>`}).join('')}
function renderMissions(filter='all'){const areas=[['all','✨','Alle'],...Object.entries(AREA).map(([k,v])=>[k,...v])];$('#areaTabs').innerHTML=areas.map(([k,ic,n])=>`<button class="area-tab ${filter===k?'active':''}" data-area="${k}">${ic} ${n}</button>`).join('');$$('.area-tab').forEach(b=>b.onclick=()=>renderMissions(b.dataset.area));const ms=currentWeek.missions.filter(m=>(filter==='all'||m.area===filter)&&unlocked(m.area==='werft'?'missionen':m.area));$('#missionGrid').innerHTML=ms.length?ms.map(m=>`<article class="card mission-card"><div class="row spread"><span class="tag ${m.resource}">${CFG.resources[m.resource]?.icon||'✨'} ${esc(m.resource)}</span><span class="small muted">⏱ ${esc(m.time)}</span></div><h3>${AREA[m.area]?.[0]||'📌'} ${esc(m.title)}</h3><p>${esc(m.task)}</p><div class="output-icons">${m.outputs.map(o=>OUTPUT[o]?.[0]||'').join(' ')}</div><button class="primary" data-mission="${m.id}">${studentOpen()?'Mission öffnen':'Mission ansehen'}</button></article>`).join(''):'<article class="card card-pad"><p>In diesem Bereich gibt es diese Woche noch keine Mission.</p></article>';$$('[data-mission]').forEach(b=>b.onclick=()=>openMission(b.dataset.mission))}
function renderMap(){const map=CFG.map;$('#mapExternal').href=map.editorUrl;$('#mapImage').src=map.image;$('#mapCaption').textContent=map.caption;$('#mapPosition').textContent=CFG.ship.position;$('#mapWeekStory').textContent=currentWeek.story;$('#mapIdeas').innerHTML=(currentWeek.council?.choices||[]).map(x=>`<div class="location-item">📍 ${esc(x)}</div>`).join('');const iframe=$('#mapIframe'),fallback=$('#mapFallback');if(map.viewerUrl){iframe.src=map.viewerUrl;iframe.classList.remove('hidden');fallback.classList.add('hidden')}else{iframe.classList.add('hidden');fallback.classList.remove('hidden')}}
function renderLogbook(){const all=[...CFG.logbook,...runtime.localLogbook].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#logbookList').innerHTML=all.map(e=>`<article class="log-entry ${e.local?'local':''}"><div class="eyebrow">${formatDate(e.date)} · Woche ${e.week||'–'}</div><h3>${esc(e.title||'Logbucheintrag')}</h3><p>${esc(e.text)}</p>${e.author?`<div class="small muted">Beitrag von ${esc(e.author)}</div>`:''}</article>`).join('')}
async function renderCouncil(){const c=currentWeek.council||{title:'Besatzungsrat',description:'',choices:[]};$('#councilTitle').textContent=c.title;$('#councilDescription').textContent=c.description;let results=Array(c.choices.length).fill(0);try{results=await syncVoteCounts(currentWeek.number,c.choices.length)}catch(error){console.warn(error)}const total=results.reduce((a,b)=>a+b,0);$('#councilState').innerHTML=runtime.councilOpen?'<span class="session-pill open">🟢 Abstimmung geöffnet</span>':`<span class="session-pill">🔒 Abstimmung geschlossen${total?` · ${total} Stimmen`:''}</span>`;$('#councilOptions').innerHTML=c.choices.map((x,i)=>`<button class="vote-card" data-vote="${i}" ${runtime.councilOpen&&studentOpen()?'':'disabled'}>${esc(x)}${!runtime.councilOpen&&total?`<div class="vote-count">${results[i]}</div>`:''}</button>`).join('');$$('[data-vote]').forEach(b=>b.onclick=()=>castVote(Number(b.dataset.vote)));renderShortlist()}
async function renderShortlist(){const list=(await dbAll()).filter(x=>x.status==='shortlist'&&x.week===currentWeek.number);$('#shortlist').innerHTML=list.length?list.map(x=>`<article class="card submission"><strong>${esc(x.missionTitle)}</strong><p>${esc(x.text||'Bild-, Zeichen- oder Audiobeitrag')}</p><span class="small muted">${esc(x.author||'ohne Namen')}</span></article>`).join(''):'<p class="muted">Noch keine Fundstücke markiert.</p>'}
