/* Animierte Glasgefäße für Antrieb, Wissen und Zusammenhalt */
const gemsState={initialized:false,scene:null,camera:null,renderer:null,clock:null,vessels:[],resizeObserver:null,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
const GEM_COLORS={antrieb:[0x52b788,0x2f7a55],wissen:[0x58a9d2,0x2876a3],zusammenhalt:[0xf4a261,0xd46e2a]};
const GEM_KEYS=['antrieb','wissen','zusammenhalt'];
const VESSEL_RADIUS=1.02, GEM_RADIUS=.205;
function gemRand(seed){let value=seed%2147483647;if(value<=0)value+=2147483646;return()=>((value=value*16807%2147483647)-1)/2147483646}
function gemTarget(index,random){const perLayer=8,layer=Math.floor(index/perLayer),slot=index%perLayer;const angle=slot*Math.PI*2/perLayer+layer*.42+random()*.2;const radius=(VESSEL_RADIUS-GEM_RADIUS-.08)*Math.sqrt(.18+.78*random());return new THREE.Vector3(Math.cos(angle)*radius,GEM_RADIUS+.13+layer*.39+random()*.035,Math.sin(angle)*radius)}
function makeVessel(key,index){const group=new THREE.Group();group.position.x=(index-1)*3.45;
  const glass=new THREE.Mesh(new THREE.CylinderGeometry(VESSEL_RADIUS,VESSEL_RADIUS*.93,2.95,36,1,true),new THREE.MeshPhysicalMaterial({color:0xeaf7fb,transparent:true,opacity:.2,roughness:.03,metalness:0,side:THREE.DoubleSide,clearcoat:1,clearcoatRoughness:.08,depthWrite:false}));glass.position.y=1.52;group.add(glass);
  const base=new THREE.Mesh(new THREE.CylinderGeometry(VESSEL_RADIUS*.93,VESSEL_RADIUS*.93,.1,36),new THREE.MeshPhysicalMaterial({color:0xd7e8ed,transparent:true,opacity:.48,roughness:.12,depthWrite:false}));base.position.y=.06;group.add(base);
  const rimMaterial=new THREE.MeshStandardMaterial({color:0xd0a642,roughness:.27,metalness:.68});
  const topRing=new THREE.Mesh(new THREE.TorusGeometry(VESSEL_RADIUS,.055,10,40),rimMaterial);topRing.rotation.x=Math.PI/2;topRing.position.y=3;group.add(topRing);
  const bottomRing=new THREE.Mesh(new THREE.TorusGeometry(VESSEL_RADIUS*.93,.035,8,36),rimMaterial);bottomRing.rotation.x=Math.PI/2;bottomRing.position.y=.08;group.add(bottomRing);
  gemsState.scene.add(group);return{key,group,gems:[],colors:GEM_COLORS[key]}}
function gemsInit(){if(gemsState.initialized)return;const canvas=$('#gems-canvas'),wrap=$('#gems-canvas-wrap');if(!canvas||!wrap)return;if(typeof THREE==='undefined'){wrap.insertAdjacentHTML('beforeend','<div class="gems-fallback">Die 3D-Schatzkammer konnte nicht geladen werden.<br>Die Zahlen darunter bleiben weiterhin verfügbar.</div>');return}
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputEncoding=THREE.sRGBEncoding;renderer.setClearColor(0x000000,0);
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,60),clock=new THREE.Clock();gemsState.renderer=renderer;gemsState.scene=scene;gemsState.camera=camera;gemsState.clock=clock;
  scene.add(new THREE.HemisphereLight(0xfff5df,0x376d83,1.05));const keyLight=new THREE.DirectionalLight(0xffffff,1.05);keyLight.position.set(4,8,6);scene.add(keyLight);const rimLight=new THREE.DirectionalLight(0xa8e1ef,.52);rimLight.position.set(-5,4,-4);scene.add(rimLight);
  const platform=new THREE.Mesh(new THREE.BoxGeometry(11.25,.34,3.35),new THREE.MeshStandardMaterial({color:0x8a572e,roughness:.8,metalness:0}));platform.position.y=-.17;scene.add(platform);
  const inset=new THREE.Mesh(new THREE.BoxGeometry(10.7,.035,2.9),new THREE.MeshStandardMaterial({color:0xb77b43,roughness:.72}));inset.position.y=.015;scene.add(inset);
  gemsState.vessels=GEM_KEYS.map(makeVessel);gemsState.initialized=true;
  const resize=()=>{const width=Math.max(1,wrap.clientWidth),height=Math.max(1,wrap.clientHeight),aspect=width/height;renderer.setSize(width,height,false);camera.aspect=aspect;camera.position.set(0,3.5,aspect<.92?18.5:aspect<1.35?14.5:10.9);camera.lookAt(0,1.35,0);camera.updateProjectionMatrix()};resize();gemsState.resizeObserver=new ResizeObserver(resize);gemsState.resizeObserver.observe(wrap);gemsUpdate(true);gemsAnimate()}
function gemsUpdate(initial=false){if(!gemsState.initialized)return;gemsState.vessels.forEach((vessel,vesselIndex)=>{const isOpen=typeof unlocked==='function'?unlocked(vessel.key):true;const wanted=isOpen?Math.max(0,Math.min(60,Number(runtime?.resources?.[vessel.key]||0))):0;const value=$(`#gemValue-${vessel.key}`),max=$(`#gemMax-${vessel.key}`),label=$(`#gemLabel-${vessel.key}`);if(value)value.textContent=isOpen?wanted:'🔒';if(max)max.textContent=isOpen?`von ${CFG.resources[vessel.key].maximum}`:'noch verschlossen';if(label)label.classList.toggle('locked',!isOpen);
    while(vessel.gems.length>wanted){const gem=vessel.gems.pop();vessel.group.remove(gem.mesh);gem.mesh.geometry.dispose();gem.mesh.material.dispose()}
    const random=gemRand(600+vesselIndex*83);const targets=Array.from({length:wanted},(_,i)=>gemTarget(i,random));
    while(vessel.gems.length<wanted){const index=vessel.gems.length,color=vessel.colors[index%2],mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(GEM_RADIUS,1),new THREE.MeshPhysicalMaterial({color,roughness:.12,metalness:.04,transparent:true,opacity:.94,clearcoat:1,clearcoatRoughness:.1,emissive:color,emissiveIntensity:.07}));const target=targets[index];mesh.position.copy(target);mesh.rotation.set(random()*Math.PI,random()*Math.PI,random()*Math.PI);if(!gemsState.reduced){mesh.position.y=initial?3.8+index*.075:4.2}vessel.group.add(mesh);vessel.gems.push({mesh,target,velocity:0,settled:gemsState.reduced,spin:(random()-.5)*3.2})}
    vessel.gems.forEach((gem,index)=>gem.target=targets[index])})}
function gemsAnimate(){if(!gemsState.initialized)return;requestAnimationFrame(gemsAnimate);const dt=Math.min(gemsState.clock.getDelta(),.05),time=gemsState.clock.getElapsedTime();gemsState.vessels.forEach((vessel,index)=>{if(!gemsState.reduced)vessel.group.rotation.y=Math.sin(time*.28+index*2.1)*.095;vessel.gems.forEach(gem=>{if(!gem.settled){gem.velocity-=9.2*dt;gem.mesh.position.y+=gem.velocity*dt;gem.mesh.rotation.x+=gem.spin*dt;gem.mesh.rotation.z+=gem.spin*.65*dt;if(gem.mesh.position.y<=gem.target.y){if(Math.abs(gem.velocity)>1.15){gem.velocity=-gem.velocity*.31;gem.mesh.position.y=gem.target.y}else{gem.mesh.position.copy(gem.target);gem.settled=true}}}else if(!gemsState.reduced){gem.mesh.rotation.y+=dt*.2}})});gemsState.renderer.render(gemsState.scene,gemsState.camera)}
const renderWithoutGems=render;render=function(...args){const result=renderWithoutGems(...args);requestAnimationFrame(()=>{if(!gemsState.initialized)gemsInit();else gemsUpdate(false)});return result};
